version: "3.9"

services: 
  django:
    build: ./project
#    command: sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
    command: python manage.py runserver 0.0.0.0:8000 
    volumes: 
      - ./project:/project
      - static_data:/project/static
    # expose: 
    #   - 8000
    ports: 
      - "8000:8000"
    environment: 
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/django
      - DEBUG=1  
    depends_on:
      - db  
  db:
    image: postgres:13-alpine
    volumes: 
      - pg_data:/var/lib/postgresql/data/
    # expose: 
    #   - 5432  
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    image: nginx:1.19.8-alpine
    depends_on: 
      - django
#    expose: 
#      - 80   
    ports: 
      - "80:80"
    volumes: 
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d
  adminer:
    image: adminer
#    restart: always
    ports:
      - 8080:8080
volumes: 
  pg_data:
  static_data:      